language: node_js
node_js:
  - '10'
before_install:
  - nvm install-latest-npm
install: yarn
script:
  - yarn test
  - yarn build
  - mv build strichliste-web-frontend
  - tar cfz strichliste-web-frontend.tar.gz strichliste-web-frontend/
deploy:
  provider: releases
  api_key:
    secure: 0xxU8j1HUn5OevC+e44ZJ+Mp6udGrnWplqts7IG8nKSQQRgmC4UuN5rZrdxatgULe1ESdli0gt6YEixRjEwVrdk7MTFL37RlUQFjEdH5tLtEfbQUczn28HhPPD3vA0kDRpXfQ6jvdYCykDvk72QVYMxeB0NLyqUTDfLxzXTxIqbThuWF9haQJUq9uYtx8wUECirkawVSUml57kWrvy/QtKOEkI9G8IsJju0WyIG24KSMLrFf0rNk0UyjZql8WYeQzJ2uHxXhZv5kobabeEsoHDsl0nN9gjzRmLrhpXrfY2YHnQjCpss0pC8EID91w34WqJfY4gaoOCnvNgz7JDZ9mGlzgmZpSGN/GCjfWFIzkNdMJBBsVJ9sArMiv9D+jelv1LbRkyJ9uLQBWtjBGkjZZ1eJmCGXBhqDLv19aiiZcqnOjR5TY0SZrHecaUP6hUCwd28XSIS2geZyO2h8Ek0Jgkxy3BcKI7NKYCJGCNBloSDgIc4yv98B7vCbHe4oaTcrNo4J0GD4eneEy6fW3lskcetwHo3ORqTTCHv9C8hUdEHH5RvppFlosJBoaQULG8grWtq7XzJ/kyGXQOypZU0lednMH7II+g/O3WCWRLIn4HfPbFY/VaGuQspbLWJcda13etCuR+NkJFOhKj0B5z3rtr63Y9fkKmaKJl4h06NtVc4=
  file: strichliste-web-frontend.tar.gz
  skip_cleanup: true
  on:
    repo: strichliste/strichliste-web-frontend
    tags: true
    branch: master
